        SELECT STD-T-FILE
	       ASSIGN TO 	DISK STD-T-DATANAME
	       ORGANIZATION	INDEXED
	       LOCK MODE	AUTOMATIC
	       ACCESS		DYNAMIC
	       RECORD KEY	STD-T-KEY
	       FILE STATUS	STD-T-STATUS.
