        SELECT SSR-T-FILE
	       ASSIGN TO 	DISK SSR-T-DATANAME
	       ORGANIZATION	INDEXED
	       LOCK MODE	AUTOMATIC
	       ACCESS		DYNAMIC
	       RECORD KEY	SSR-T-KEY
	       FILE STATUS	SSR-T-STATUS.
