        SELECT STD-T-FILE
	       ASSIGN TO 	DISK STD-T-DATANAME
	       ORGANIZATION	INDEXED
	       LOCK MODE	AUTOMATIC
	       ACCESS		DYNAMIC
	       RECORD KEY	STD-T-KEY
	       ALTERNATE KEY	STD-T-ALT-KEY1 = 
				STD-T-NAME, STD-T-KEY
	       ALTERNATE KEY    STD-T-ALT-KEY2 =
				STD-T-AGE, STD-T-NAME, STD-T-KEY
               ALTERNATE KEY    STD-T-ALT-KEY3 =
				STD-T-CY-KEY, STD-T-NAME, STD-T-KEY
	       FILE STATUS	STD-T-STATUS.
